//====FUNCTIONS====// 

// SPIFFS
#define SPIFFS_USE_FUNCTIONALITY
#define SPIFFS_CHECK
#define SPIFFS_CHECK_ON_START
#define SPIFFS_PARTITION_LABEL "data_storage"
#define SPIFFS_CLEAR_FILE_AFTER_READ_FROM
#define SPIFFS_MAX_FILES 10

// #define SPIFFS_LOGS

// #define PRINT_PACKAGE
#define VORONEZH_UTC_CORRECTION
// #define ENABLE_TIME_CONVERTER_LOGS

//===== PARAMS =====//

#define SPIFFS_FILE_PATH "/spiffs/norbi.txt"

#define HTTP_BUFFER_SIZE 4096

// WARNING! COULD BE STACK OVERFLOW, LOOK AT CONFIG_ESP_MAIN_TASK_STACK_SIZE
// in skkconfig / idf.py menuconfib  
#define NUMBER_OF_SYMBOLS_IN_SPIFFS_FILE_TO_READ_FROM 4000